name: Generate ASCII Artwork

on: push

jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps: 
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Executy Cowsay cmd
              run: conway -f dragon "Run for Cover, I am a Dragon...RAWR" >> dragon.txt

            - name: Sleep for 30 seconds
              run: sleep 30

    test_job2:
      needs: build_job1
      runs-on: ubuntu-latest
      steps: 
          - name: Sleep for 10 seconds
            run: sleep 10

          - name: Test file exists
            run: grep -i "dragon" dragon.txt
        
      deploy_job3:
        needs: test_job2
        runs-on: ubuntu-latest
        steps: 
            - name: Read File
              run: cat dragon.txt

            - name: Test file exists
            run: echo Deploying...