name: Exploring Variables and Secrets

on: 
    push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: jhashem35
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: docker build -t ${{ env.CONTAINER_REGISTRY}}/dockerUsername/$IMAGE_NAME:latest

        - name: Docker login
          env:
            DOCKER_PASSWORD: s3cUrePaSsw0rd
          run: docker login --username=$DOCKER_USERNAME -password=$DOCKER_PASSWORD

        - name: Docker Publish
          run: docker push docker.io/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: docker ru -d -p 8080:80 docker.io/$DOCKER_USERNAME/$IMAGE_NAME:latest